# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9cHQxqJDKsV9sM939gk-sTMGMgU4hU_
"""

name = input("Enter your name: ")
mobile = input("Enter your mobile number: ")

ticket_type = input("Enter ticket type (Regular/VIP): ").lower()

if ticket_type == "regular":
    price = 500
elif ticket_type == "vip":
    price = 1000
else:
    print("Invalid ticket type")
    exit()

try:
    quantity = int(input("Enter number of tickets: "))
except:
    print("Invalid number")
    exit()

total = price * quantity

discount = 0
if total > 3000:
    discount = total * 0.10

final_amount = total - discount

print("\n----- BILL -----")
print("Name:", name)
print("Mobile: " , mobile)
print("Ticket Type:", ticket_type.capitalize())
print("Tickets:", quantity)
print("Total:", total)
print("Discount:", discount)
print("Final Amount:", final_amount)
